### PR TITLE
Fix dead link to Webkit C++ style guide

### PR DESCRIPTION
**Pull request by aprotyas**

### CODE REVIEW

**Comment by aprotyas** [comment]
Nvm, old link still works.

**Comment by motine** [comment]
hey @aprotyas, i am not sure about this merge request. i think the link is broken. should i reopen and merge?

**Comment by aprotyas** [comment]
@motine when I made that commit, the old link wasn't working.. but it seems to be fine on my end now? If the old link isn't working on your end, feel free to open and merge this

**Comment by motine** [comment]
yep, it does not work for me. i guess we are on the safe side to merge this. thank you for your contribution!

**Pull request merged**
